### ISSUE TITLE
Add Airline support

### ISSUE THREAD

**Issue by mihaelartz** [lifepillar/vim-gruvbox8#10]

**Comment by lifepillar** [comment]
I am not keen to add support for something I do not use. You could copy the relevant files from Gruvbox’s repository into your `~/.vim/autoload` folder. Would that work for you?

Orherwise, I welcome pull requests,

**Comment by mihaelartz** [comment]
@lifepillar I tried but, not working.

**Comment by lifepillar** [comment]
Ok, I’ll have a look at it.

**Comment by lifepillar** [comment]
It works for me after renaming `autoload/airline/themes/gruvbox.vim` into `autoload/airline/themes/gruvbox8.vim` and replacing each occurrence of `gruvbox` with `gruvbox8` inside that file.

If you apply such changes, I suggest that you send a pull request to https://github.com/vim-airline/vim-airline-themes, which collects several other Airline themes.

**Comment by mihaelartz** [comment]
@lifepillar Can not it be a problem to attach the file to ```https://gist.github.com/```? Tried everything, but do not work.

Sorry for my bad English. Thanks.

**Comment by lifepillar** [comment]
Here you are: https://gist.github.com/lifepillar/cc3236a47bbba0261283f43f73074932.

Save the file as `~/.vim/autoload/airline/themes/gruvbox8.vim` (create the intermediate directories if necessary).

**Comment by mihaelartz** [comment]
@lifepillar Thanks.
