### ISSUE TITLE
Digraph table characters hard to see

### ISSUE THREAD

**Issue by aos** [lifepillar/vim-gruvbox8#12]
When issuing the command `:digraphs`, the output is this:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/25783780/63032579-15ab0200-be84-11e9-8bf1-37831737c046.png">

The digraph characters are hard to see. I understand that the highlight group for these is `SpecialKey`. I can work on this later this week, by just increasing the contrast, but is there anything else I should know about it?

**Comment by lifepillar** [comment]
I've changed `SpecialKey`'s foreground from `bg2` to `gret`. Does that help?

**Comment by lifepillar** [comment]
>anything else I should know about it?

In recent Vim versions, `digraphs!` groups symbols by category :)

**Comment by aos** [comment]
Looks much better -- thanks !

> In recent Vim versions, digraphs! groups symbols by category :)

That's awesome. But I'm using neovim and it hasn't been ported over yet!
