### ISSUE TITLE
Few enhancements?

### ISSUE THREAD

**Issue by oponkork** [lifepillar/vim-gruvbox8#14]
I recently switched from [gruvbox-community](https://github.com/gruvbox-community/gruvbox) and I am liking the slightly different color palette. But there are two things which I find missing.

1. It's very hard to figure out on what highlighted match your cursor is? Earlier I had `let g:gruvbox_hls_cursor='blue'` in gruvbox-community which made it easier to see!

2. An option to disable bold  text, which again I could disable by `let g:gruvox_bold=0` earlier.

Will it be possible to have these features in gruvbox8?

**Comment by lifepillar** [comment]
>It's very hard to figure out on what highlighted match your cursor is? Earlier I had let `g:gruvbox_hls_cursor='blue'` in gruvbox-community 

AFAICS, setting `g:gruvbox_hls_cursor="blue"` in Gruvbox does not automatically make the cursor blue; I also have to create a mapping that invokes `GruvboxHlsShowCursor()`. I think these tweaks are better handled on the user's side, e.g. (untested):

```vim
fun! ToggleGruvboxCursor()
  set invhlsearch
  execute "hi! Cursor" (&hlsearch ? "guibg=#83a598 gui=NONE" : "guibg=NONE gui=inverse"
endf

nnoremap <silent> <leader>oh :<c-u>call ToggleGruvboxCursor()<cr>
```

>An option to disable bold text, which again I could disable by let g:gruvox_bold=0 earlier.

Yes, I think I may add that.

**Comment by oponkork** [comment]
> AFAICS, setting `g:gruvbox_hls_cursor="blue"` in Gruvbox does not automatically make the cursor blue

I just used the option as mentioned [here](https://github.com/gruvbox-community/gruvbox/wiki/Configuration#ggruvbox_hls_cursor) and it does make the curser blue when search is highlighted. 

> Yes, I think I may add that.
Ah yes, thanks a lot for that.

**Comment by lifepillar** [comment]
>I just used the option as mentioned here and it does make the curser blue when search is highlighted.

There is no code in Gruvbox that automatically changes the cursor when `hlsearch` is toggled: you need to invoke `GruvboxHlsShowCursor()` or `GruvboxHlsHideCursor()` to do that. What `let g:gruvbox_hls_cursor="blue"` does is set `IncSearch` to blue so that, while searching, the *currently selected match* (not the cursor) becomes blue.

If you want to set `IncSearch` to blue the simplest way is to put something like this in your `vimrc`:

```vim
colorscheme gruvbox8
hi! IncSearch guifg=#83a598 guibg=#282828 gui=reverse
```

**Comment by oponkork** [comment]
> while searching, the currently selected match (not the cursor) becomes blue.

Aah, I understand now. Thanks a lot for the clarification. That's what I meant.

**Comment by lifepillar** [comment]
Please upgrade to the current master: now setting `g:gruvbox_bold` to `0` suppresses bold fonts everywhere.

**Comment by oponkork** [comment]
Thanks a lot for accommodating my request so quickly. I am using `vim/neovim` in terminal, and according to the updated docs I put `set t_md=` in my configuration file. It works as expected on `vim`. `neovim` on the other hand stays the same, and `:help t_md` on `neovim` doesn't return anything.

**Comment by lifepillar** [comment]
Ah, Neovim has removed termcap options. Your best bet is to disable boldface through your terminal settings. Otherwise, build a custom terminfo database or remove `bold` from all `cterm` options, as you have done.

**Comment by oponkork** [comment]
> Ah, Neovim has removed termcap options. Your best bet is to disable boldface through your terminal settings. Otherwise, build a custom terminfo database or remove `bold` from all `cterm` options, as you have done.

Yeah, I will stick with the way I have done it, thanks a lot.
