### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by wsdjeg** [lifepillar/vim-gruvbox8#15]
Is there any differences of the colorscheme template between this repo and https://github.com/morhetz/gruvbox? How about add license?

**Comment by lifepillar** [comment]
Look in the source files in the `colors` directory: those are distributed under Vim's license.

As for the differences: if you mean visual differences, yes, there are quite a bit, although the color palette is the same and the overall look is, well, Gruvbox. See the screenshots in the Readme.

If you mean differences in the code: Gruvbox 8 is generated automatically using my [Colortemplate](https://github.com/lifepillar/vim-colortemplate) plugin. There is little resemblance with the original code.

**Comment by wsdjeg** [comment]
ok, thanks.
