### ISSUE TITLE
Set Airline Theme

### ISSUE THREAD

**Issue by vinicius507** [lifepillar/vim-gruvbox8#17]
Greetings,

In the pictures in README.md there seems to be some status line plugin. I'd like to know which one and how can I set the theme to gruvbox8. 

Thanks in advance,

MyriadAsura

**Comment by lifepillar** [comment]
I do not use status line plugins. You may find the code for my status line in my [vimrc](https://github.com/lifepillar/vimrc/blob/cec1eaf416ba9c89e4a792502ddee2a3d06d275a/vimrc#L211).

For highlighting, my status line defines few custom highlight groups (called `NormalMode`, `InsertMode` and so on). My color schemes already contain definitions for such groups, but you may link them to whatever you want (as I do for some [other color schemes](https://github.com/lifepillar/vimrc/blob/master/after/themes/seoul256.vim)).

There's an [open pull request](https://github.com/lifepillar/vim-gruvbox8/pull/16) to add support for Lightline, which I need to review and then I will likely merge. After that is merged, you should be able to use Lightline out of the box with this color scheme.

**Comment by vinicius507** [comment]
Thank you for your attention and your awesome theme. I will look into your vimrc file!

**Comment by binarypie** [comment]
@vinicius507 The original gruvbox airline works fine out of the box as far as I can tell. I've opened a PR to further the discussion with @lifepillar. Let me know if you run into any issues.

**Comment by vinicius507** [comment]
I'll try adding it later to my dotfiles and see if  I run into any troubles. Thank you!
