### ISSUE TITLE
Missing comma in template

### ISSUE THREAD

**Issue by scottopell** [lifepillar/vim-gruvbox8#19]
https://github.com/lifepillar/vim-gruvbox8/blob/05d18a11098417b85cd57f14c4355d7e658de605/templates/_plugins#L58

This line:
```vimscript
if get(g: 'gruvbox_invert_indent_guides', 0)`
```
is missing a comma after the `g:` in this function call.

This causes a syntax error when the variable `indent_guides_auto_colors` is set to true.

**Comment by lifepillar** [comment]
Thanks for reporting!
