### ISSUE TITLE
E121: Undefined variable and E15: Invalid expression errors

### ISSUE THREAD

**Issue by fszymanski** [lifepillar/vim-gruvbox8#2]
I get this error when I set `g:gruvbox_plugin_hi_groups` to `1`:
```
Error detected while processing /home/???/.local/share/nvim/bundle/vim-gruvbox8/colors/gruvbox8_hard.vim:
line  235:
E121: Undefined variable: #504945
E15: Invalid expression: #504945
line  850:
E121: Undefined variable: #d5c4a1
E15: Invalid expression: #d5c4a1
```
I think you must use strings in the templates.
Example [_plugins.colortemplate line: 73](https://github.com/lifepillar/vim-gruvbox8/blob/master/templates/_plugins.colortemplate#L73):
```
let g:indentLine_color_gui = '@guibg2'
```

**Comment by lifepillar** [comment]
Good catch, thanks!

One of the reasons I created gruvbox8 is to avoid using filetype and plugin specific highlight groups, so that part has not been tested much. Thanks again!
