### ISSUE TITLE
let g:gruvbox_italicize_strings=0 does NOT appear to be working

### ISSUE THREAD

**Issue by casonadams** [lifepillar/vim-gruvbox8#20]
`let g:gruvbox_italicize_strings = 0`

This setting doesn't remove string ltalicization

nvim 0.5
alacritty 0.5
fedora 32

**Comment by lifepillar** [comment]
I cannot reproduce it. Also using Alacritty (in macOS).

Are you (re)loading the color scheme *after* setting `g:gruvbox_italicize_strings`?

**Comment by casonadams** [comment]
So if I run `:colorcheme gruvbox8` then things are fine.  But if I close out the editor and reopen then it reverts to not working.

Using these settings.
```
set termguicolors
colorscheme gruvbox8
set background=dark
let g:gruvbox_transp_bg=0
let g:gruvbox_italicize=0
let g:gruvbox_italicize_strings=0
let g:gruvbox_bold=0
```
Before call
![image](https://user-images.githubusercontent.com/17597548/94284863-34e1e300-ff10-11ea-846d-db14b2e8188d.png)

After call
![image](https://user-images.githubusercontent.com/17597548/94284911-44f9c280-ff10-11ea-9b29-d8280f2ba528.png)

**Comment by lifepillar** [comment]
Move `colorscheme gruvbox8` to the bottom.

In general, any option must be set _before_ loading the color scheme.

**Comment by casonadams** [comment]
Awesome that corrected it!  Funny I was just thinking maybe I should try that!

**Comment by lifepillar** [comment]
…including the background (otherwise, the color scheme may be loaded twice—not an error per se, but useless).
