### ISSUE TITLE
Add Support for coc-vim

### ISSUE THREAD

**Issue by casonadams** [lifepillar/vim-gruvbox8#21]
Add colorsetting for the following:
```
CocErrorSign 
CocWarningSign 
CocInfoSign 
CocHintSign 
CocErrorFloat 
CocWarningFloat 
CocInfoFloat 
CocHintFloat 
CocDiagnosticsError 
CocDiagnosticsWarning 
CocDiagnosticsInfo 
CocDiagnosticsHint 

CocSelectedText 
CocCodeLens 

CocErrorHighlight
CocWarningHighlight
CocInfoHighlight
CocHintHighlight
```

See [gruvbox](https://github.com/morhetz/gruvbox/blob/040138616bec342d5ea94d4db296f8ddca17007a/colors/gruvbox.vim)
lines `895 - 914`

**Comment by casonadams** [comment]
These settings seems to look good with the theme.  But just a suggestion.

```
hi CocErrorSign guibg=#282828 guifg=#fb4934
hi CocWarningSign guibg=#282828 guifg=#fabd2f
hi CocInfoSign guifg=#83a598
hi CocHintSign guifg=#504945
hi CocErrorFloat guifg=#fb4934
hi CocWarningFloat guifg=#fabd2f
hi CocInfoFloat guifg=#83a598
hi CocHintFloat guifg=#d3869b
hi CocSelectedText guibg=#3c3836 guifg=#282828
hi CocCodeLens guifg=#504945
```

**Comment by lifepillar** [comment]
What do I have to install to test that?

**Comment by casonadams** [comment]
You interested in a docker container?

**Comment by lifepillar** [comment]
No, I'd rather like to know which plugin provides those highlight groups's names. I haven't followed recent development of completion plugins (is it completion?), and I am a bit lost through so many "coc" plugins out there.

**Comment by casonadams** [comment]
https://github.com/neoclide/coc.nvim

Then for each language I care about I add the coc extension for it.

In my case I’m programming primarily in rust so it uses rust-analyzer under the covers.

If you want to have a look at my vim dotfiles and config files see here https://github.com/casonadams/linux-dotfiles/tree/master/dotfiles/config/nvim

**Comment by lifepillar** [comment]
I have added the highlight as you suggest. Feel free to reopen if something is wrong.
