### ISSUE TITLE
gruvbox8 theme for bat?

### ISSUE THREAD

**Issue by smartding** [lifepillar/vim-gruvbox8#22]
I'm using bat for text previewing in ranger, fzf.vim, etc.
I wonder if there's a gruvbox8 theme for bat?

**Comment by lifepillar** [comment]
What's bat?

**Comment by smartding** [comment]
> What's bat?

bat is a cat(1) clone with syntax highlighting and Git integration. it's often embedded in other programs for text previewing.
https://github.com/sharkdp/bat

**Comment by lifepillar** [comment]
Ah ok. No, this repo is strictly only for Vim. But, given the popularity of Gruvbox, it is quite likely that there is a theme for that tool… In fact, have you seen [this issue](https://github.com/sharkdp/bat/issues/976)?

Anyway, I am closing this, because it is out of scope of this project.
