### ISSUE TITLE
Turn of italics for String

### ISSUE THREAD

**Issue by sQVe** [lifepillar/vim-gruvbox8#23]
Hey :wave:,

_Firstly I'd like to give a thank you for this very speedy gruvbox theme!_

I don't want *italics* for my **strings** and tried disabling it with `let g:gruvbox_italicize_strings = 0`. This disables italics for **strings** but also for **specials**, see https://github.com/lifepillar/vim-gruvbox8/blob/master/colors/gruvbox8.vim#L152.

My guess is that this is a bug? Adding this the below :point_down: to my vimrc solves it for me at least.

```vimscript
" Turn of italics for strings.
hi! String gui=NONE cterm=NONE
```

**Comment by sQVe** [comment]
By the way, I'm happy to create a PR if you agree with that this behavior is intended or not.

**Comment by lifepillar** [comment]
I think I have inherited that part from the original Gruvbox. I have no strong opinion about it: I may change the option to affect only `String`.

**Comment by lifepillar** [comment]
Yes, that's how the original Gruvbox [defined it](https://github.com/morhetz/gruvbox/blob/bf2885a95efdad7bd5e4794dd0213917770d79b7/colors/gruvbox.vim#L573). I don't know, I guess there was a reason why `Special` was included, and I'd lean towards backward compatibility.

>Adding this the below 👇 to my vimrc solves it

This is the way you are supposed to customize color schemes, after all. In retrospect, I should not have included any option in my fork.

I propose to leave things as they are and leave this issue open. If others come supporting your view, I will update the option.

**Comment by sQVe** [comment]
@lifepillar I still find this confusing but :man_shrugging:. Works for me to override it manually.

This is actually something I gave a bit of thought yesterday. Wouldn't it be nice if `gruvbox8` just provided the **gruvbox** base theme but no overrides or _extras_ for plugins etc. Instead we create a cookbook where you easily can copy and paste `highlight` for plugins or overrides. This would also enable PRs for `vim-airline` themes etc without having to judge if it is bloat or not. My feeling is that this would inline perfectly with the speed is first class citizen of `gruvbox8`.

**Comment by lifepillar** [comment]
>Wouldn't it be nice if gruvbox8 just provided the gruvbox base theme but no overrides or extras for plugins etc.

It would be a good idea to provide a streamlined Gruvbox-like color scheme, but it would not be wise to drastic changes to Gruvbox8 at this point: in particular, removing support for plugins/filetypes would be disrupting for many users.

It is very easy, however, to customize Gruvbox8. Just install [Colortemplate](https://github.com/lifepillar/vim-colortemplate), edit `_common` and remove/comment out the following lines:

```
Include: _plugins
Include: _filetypes
```

Then, rebuild the color schemes.

A new, simplified, version of Gruvbox8 is something I am considering (Gruvbox9? For Vim 9?). Possibly, a holiday project…

**Comment by sQVe** [comment]
Closing this as I got the answers I needed.
