### ISSUE TITLE
upon vim startup, bright color theme for a split second, then dark?

### ISSUE THREAD

**Issue by christianparpart** [lifepillar/vim-gruvbox8#24]
Hey,

first: many thanks for the great colorscheme!

I am having one issue though that I'd like to understand.

With the following settings:

```vim
Plug "ifepillar/vim-gruvbox8"
" ...
colorscheme gruvbox8_hard
```

Now, if I open vim via tmux, I will see the bright theme.

If I open vim outside tmux I see the bright theme at startup for a very split moment, and then the dark (expected) theme.

I wonder what is happening internally of vim-gruvbox8 to do that, would you mind giving me some hints?

Many thanks, and marry Christmas.

**Comment by lifepillar** [comment]
Are you setting the background (`set background=dark`) in your `vimrc`? If not, I think you should. If that is not the issue: which Vim's (or Neovim's) version? What's the output of `:echo has('patch-8.0.0616')`?

**Comment by christianparpart** [comment]
the patch `8.0.0616` is actually applied (echo prints `1`).
`set background=dark` fixes the issue by not flickering in the beginning. But IMHO that's not telling me yet why it flickers without it in the first place. On tmux (without `set background=dark` it remains bright while it just shortly flickers bright immediately following the dark background. So why is it switching to dark on non-tmux sessions then in the first place (i.e. why does `set background=dark` avoid the flicker on non-tmux sessions).?

**Comment by lifepillar** [comment]
Does that happen with `vim --clean -u vimrc_minimal`, where `vimrc_minimal` just adds Gruvbox8's path to `rtp` and loads the color scheme? Does that happen with other dark color schemes? This is to narrow down the problem.

**Comment by ynsmrsk** [comment]
> Does that happen with `vim --clean -u vimrc_minimal`, where `vimrc_minimal` just adds Gruvbox8's path to `rtp` and loads the color scheme? Does that happen with other dark color schemes? This is to narrow down the problem.

I have the same problem and when using `-clean -u vimrc_minimal` it does not flicker. What's the problem you think?

**Comment by lifepillar** [comment]
Which version of Vim (including patch level)?

You may try adding part of your `vimrc` configuration to the minimal vimrc until you reproduce the issue.

**Comment by ynsmrsk** [comment]
I solve the problem by changing some config lines order. My issue was not about the white theme actually.
I downloaded the gruvbox.vim theme rather than install it via plugin manager. 

And using it like this with no problem right now:
`
set termguicolors
let g:gruvbox_contrast_dark = "hard"

color gruvbox

hi VertSplit guibg=#212526 gui=none
hi StatusLine   guifg=none  guibg=#212526 gui=none
hi StatusLineNC guifg=none guibg=#212526  gui=none
hi Cursorline guibg=#212526
hi CursorlineNR guibg=#212526
`
