### ISSUE TITLE
Treesitter support

### ISSUE THREAD

**Issue by nosed1ve** [lifepillar/vim-gruvbox8#27]
First off, great theme, been using it for a while and the startup time difference is noticeable.

Seeing as there is support for a variety of plugins already, supporting treesitter explicitly would be great. There are already quite a few colorschemes explicitly supporting treesitter. 

Just bear in mind, treesitter is a neovim only tool, and the integration will ship with neovim in the 5.0 release.

**Comment by lifepillar** [comment]
Not using treesitter or Neovim myself, but I would accept a pull request.

**Comment by nosed1ve** [comment]
I would not mind giving it a shot after I get more time on my hands, but honestly, I am not the best at deciding things like colours. Keep in mind that Treesitter support is not necessary, one can use the default highlight groups too, but explicitly styling the colours to look good with Treesitter would be nice.

If no one else can do it, I'll give it a shot in my free time,  just that I don't know if my colours will be the best.

**Comment by lifepillar** [comment]
I think it would be good to have an initial proposal. Once in place, that can be adjusted by other users.

**Comment by nosed1ve** [comment]
Sounds alright to me, I'll try to come up with something when I have time.
