### ISSUE TITLE
The theme seems to not work

### ISSUE THREAD

**Issue by Acelya-9028** [lifepillar/vim-gruvbox8#28]
Hello, I use the last version of Neovim in Neovide on Windows 10 and I can't get the theme to work.

![arf](https://user-images.githubusercontent.com/45818681/107098525-b24b2780-680f-11eb-9821-f3cf8ebd90bc.png)

I tried several things but the only one that works is to call "colorscheme gruvbox8" by hand once nvim started so it's not really usable.

Use Nvim in another terminal like Powershell or Alacritty is the same.

**Comment by Acelya-9028** [comment]
Hum, ok I see on your vim-solarized8 that I need to set `set termguicolors before` and it works, thanks, but there is another problem:

![rearf](https://user-images.githubusercontent.com/45818681/107099452-00612a80-6812-11eb-88de-72ebd0a7cc18.png)

As you can seem, an another font is used for strings and comments and it's really weird. I use `set guifont=CaskaydiaCove\ NF:h15`.

**Comment by lifepillar** [comment]
Try putting this in your `vimrc`:

```vim
let g:gruvbox_italics = 0
```

before loading the color scheme. Does that fix your font issue?

**Comment by Acelya-9028** [comment]
Yes, it's good with `let g:gruvbox_italics = 0` before `colorscheme gruvbox8`, thank you.
