### ISSUE TITLE
missing keyword highligh in float window

### ISSUE THREAD

**Issue by GopherJ** [lifepillar/vim-gruvbox8#29]
while using vim-gruvbox8 together with coc-cmake I found there are some missing highlights on keywords

gruvbox:
![image](https://user-images.githubusercontent.com/33961674/107487657-5db5fc80-6bc1-11eb-9d92-f2e6a1934f37.png)

gruvbox8:
![image](https://user-images.githubusercontent.com/33961674/107487763-79b99e00-6bc1-11eb-811b-a416e8f98d5d.png)

**Comment by lifepillar** [comment]
Does

    let g:gruvbox_plugin_hi_groups = 1

change anything?

Is that Neovim?

**Comment by GopherJ** [comment]
@lifepillar yes it's neovim

**Comment by lifepillar** [comment]
Closing for lack of feedback. Feel free to reopen and provide more information if necessary.
