### ISSUE TITLE
Transparent background support

### ISSUE THREAD

**Issue by timsofteng** [lifepillar/vim-gruvbox8#30]
Hey. Can I somehow set transparent background to working with my transparent terminal?

**Comment by lifepillar** [comment]
Put this in your `vimrc`:

    let g:gruvbox_transp_bg = 1

**Comment by timsofteng** [comment]
> Put this in your `vimrc`:
> 
> ```
> let g:gruvbox_transp_bg = 1
> ```

awesome. thanks. it works. can be closed.
