### ISSUE TITLE
Failed to disable italics

### ISSUE THREAD

**Issue by 26chk** [lifepillar/vim-gruvbox8#32]
I want to set it as the default font, but I don’t want to set italics
I used the option but it didn’t work

let g:gruvbox_italicize_strings = 0

let g:gruvbox_italics = 0

How should I do？
![Screenshot_20210403_145314](https://user-images.githubusercontent.com/61009000/113471066-725d9500-948c-11eb-8b95-1218d9bcf9ac.jpg)

**Comment by lifepillar** [comment]
There is no `g:gruvbox_italicize_strings` in Gruvbox 8. To disable italics, you must set the other option before loading the color scheme. In your `vimrc`:

```vim
let g:gruvbox_italics = 0
colorscheme gruvbox8
```

If that does not solve your issue, please provide (1) some information about your environmen, and (2) a minimal `vimrc` to reproduce your issue.
