### ISSUE TITLE
Changing colors for lsp warnings and errors

### ISSUE THREAD

**Issue by sainad2222** [lifepillar/vim-gruvbox8#34]
Errors and warning given by lsp are all white. With `gruvbox-community/gruvbox` If we add 
```
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
``` 
this seems to work but not working for gruvbox8. Am I doing something wrong?
My terminal is alacrity, I also tried in gnome-terminal

**Comment by lifepillar** [comment]
Community gruvbox has added support for [LSP's highlight groups](https://github.com/gruvbox-community/gruvbox/blob/42668ea643d56729467fb79c1a0a5e30289fe590/colors/gruvbox.vim#L775). I can do the same.

**Comment by lifepillar** [comment]
I have added support for LSP in the current master. Can you please test it?

**Comment by lifepillar** [comment]
Btw, you need to enable plugin-specific highlight group by putting this in your `vimrc`:

```vim
let g:gruvbox_plugin_hi_groups = 1
```

**Comment by sainad2222** [comment]
It has no effect for me. For you reference [link](https://github.com/sainad2222/dotfiles/blob/master/init2.vim) to my nvimrc if I am doing something wrong in my config. If I do `set termguicolors` then I am getting required colors on warnings/errors but that's changing whole other code to white

**Comment by lifepillar** [comment]
You should set `g:gruvbox_plugin_hi_groups` *before* loading the color scheme.

**Comment by lifepillar** [comment]
Also, is you (un)set `termguicolors`, do so *before* loading the color scheme.

**Comment by sainad2222** [comment]
Thanks. I was setting it after loading colorscheme. Now it's fixed.
