### ISSUE TITLE
Something wrong with neovim's popup color

### ISSUE THREAD

**Issue by timsofteng** [lifepillar/vim-gruvbox8#35]
Hello. Something changed in neovim's popups displaying.
Look at the screen please
![image](https://user-images.githubusercontent.com/51912173/115752791-2030d500-a3a3-11eb-9162-a4ccfa1597f9.png)

Can't be recognizible

**Comment by lifepillar** [comment]
Is this a regression for you? That is, did popups used to look right before? If so, can you try finding which commit is to blame?

**Comment by timsofteng** [comment]
Looks like it's fine now
![image](https://user-images.githubusercontent.com/51912173/122058446-4ba8cc80-cdf4-11eb-8413-6b6b09439fe2.png)
I'm closing issue
