### ISSUE TITLE
Fallback colors

### ISSUE THREAD

**Issue by cipherlogs** [lifepillar/vim-gruvbox8#39]
Hello,

I really hope if you can help me figure out how do you make your theme fallback to 2 colors

do you use

set t_Co=2 

I tried it and it didn't work for me. Thank you

**Comment by lifepillar** [comment]
Try `:set t_Co=` (no value) or `:set t_Co=0`.

**Comment by maryylee** [comment]
Hello, thank you so much for your reply.

I have tried it but nothing changes.

I made sure that set termguicolors isn't active in my vimrc
and I also tried to start vim with "vim -c "set t_Co=" but the colors are all messed up
they are not like the ones you have attached in your readme repo

I have also tried to set my $TERM to vt100


I'm using Alacritty btw...

I really hope we can solve this problem.

**Comment by lifepillar** [comment]
Save this as `min-vimrc.vim`:

```vim
set nocompatible
set runtimepath+=<CHANGE TO PATH TO>/gruvbox8
set notermguicolors
set t_Co=
colorscheme gruvbox8
```

Run with `vim --clean -u ./min-vimrc.vim`. I get a black and white Vim in Alacritty.

Are you sure that have set `notermguicolors`?

**Comment by lifepillar** [comment]
> Are you sure that you have set `notermguicolors`?

…*before* loading the color scheme.

**Comment by maryylee** [comment]
Hello, thank you so much for your help,

I have tried everything you said, yes the colors do get stripped but the outcome is nowhere near what you have on your B&W repo

I don't know why!

**Comment by lifepillar** [comment]
>the colors do get stripped but the outcome is nowhere near what you have

Do you mean, with the minimal `vimrc` above? Well, that's… minimal. You need to enable at least syntax highlighting. Try with this:

```vim
" Minimal vimrc
set nocompatible
set runtimepath+=<PATH TO>/gruvbox8
set notermguicolors
set t_Co=
syntax enable
filetype plugin indent on
set number relativenumber
set laststatus=2
set showtabline=2
set foldmethod=marker
set foldenable
colorscheme gruvbox8
```

This is a screenshot from Alacritty with the configuration above:

![bw-vim](https://user-images.githubusercontent.com/1193314/120094477-eaf57080-c120-11eb-83c9-8acfaf55041c.jpg)

**Comment by lifepillar** [comment]
Closing as not reproducible.
