### ISSUE TITLE
the color of startify not normal

### ISSUE THREAD

**Issue by taigacute** [lifepillar/vim-gruvbox8#4]
hi, i use gruvbox8, nice colorscheme. but i found the color not normal .you  can see this pic
![1123](https://user-images.githubusercontent.com/41671631/56259507-e2d74400-6105-11e9-9f37-eb55ee278505.png)

i found the color in ` _plugins.colortemplate `
```
# Startify {{{
StartifyBracket                  fg3    none
StartifyFile                     fg1    none
StartifyNumber                   blue   none
StartifyPath                     grey   none
StartifySlash                    grey   none
StartifySection                  yellow none
StartifySpecial                  bg2    none
StartifyHeader                   orange none
StartifyFooter                   bg2    none
# }}}
```
the `startify Header` is orange but i got green?  

## my config
i use dein 
```
[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
let g:gruvbox_filetype_hi_groups = 1
let g:gruvbox_plugins_hi_groups = 1
'''
colorscheme gruvbox8_hard
```
i change the  value of `g:gruvbox_plugins_hi_groups` but nothing change

**Comment by lifepillar** [comment]
There is a typo in your configuration. Please replace:

    let g:gruvbox_plugins_hi_groups = 1

with

    let g:gruvbox_plugin_hi_groups = 1

**Comment by taigacute** [comment]
sorry  i will try it

**Comment by taigacute** [comment]
nothing to change
