### ISSUE TITLE
Lua port

### ISSUE THREAD

**Issue by timsofteng** [lifepillar/vim-gruvbox8#44]
Hey. I see you care about perfomance in your colorscheme. I heard lua-based plugins could be even faster! Neovim 0.5 supports it.
Do you have any plans to port this scheme to lua? Is it make sense?

**Comment by lifepillar** [comment]
I am not using Neovim currently, so the short answer is no.

Some general remarks. Neovim and Vim have taken two roads that are far and far apart, IMO. In particular, Neovim went with Lua, but Vim has Vim9 script. It becomes more and more difficult for plugin developers to support both programs. Some may want to do it. Not me.

So, the best approach is to fork this project and create a Lua-based version for Neovim. This way, each project can have dedicated people working on it, the codebase will stay focused on one platform, and each project can follow the developments of the corresponding editor.

"Universal" plugins are going to become ever more cluttered as time goes by. At least, this is the way I see it now.
