### ISSUE TITLE
git gutter signs are too attractive

### ISSUE THREAD

**Issue by GopherJ** [lifepillar/vim-gruvbox8#46]
normal gruvbox looks like the following
![image](https://user-images.githubusercontent.com/33961674/130306300-2f87d09e-31d1-4e80-95d9-e32ae773a5cd.png)

**Comment by GopherJ** [comment]
![image](https://user-images.githubusercontent.com/33961674/130306311-11c33232-8b64-4fdd-8602-c1b3ba6305e1.png)

**Comment by lifepillar** [comment]
That depends on which highlight group is associated to a sign when it is defined (see `:help sign-commands`, `texthl` attribute).

Gruvbox 8 has some definitions for gitgutter, but, differently from the original Gruvbox, they are not enabled by default. You need to add this to your `vimrc`:

```vim
let g:gruvbox_plugin_hi_groups = 1
```

Alternatively, you may redefine gitgutter's highlight groups directly: for that, refer to gitgutter's help file (`:help gitgutter-highlights`).

**Comment by lifepillar** [comment]
Closing as stale. I have checked GitGutter's definitions in the colorscheme and they look fine to me. As I said above, they must be enabled by setting `g:gruvbox_plugin_hi_groups` to `1`. If that does not achieve the desired result, it is always possible to [override a colorscheme](https://github.com/vim/colorschemes/wiki/How-to-override-a-colorscheme%3F)'s choice for some highlight groups in one's `vimrc.
