### ISSUE TITLE
sometimes no colorscheme anymore

### ISSUE THREAD

**Issue by GopherJ** [lifepillar/vim-gruvbox8#47]
![image](https://user-images.githubusercontent.com/33961674/130310506-71e3eaba-ee48-4c19-ba0d-2957b4b4470f.png)

**Comment by GopherJ** [comment]
I didn't have this problem in normal gruvbox

**Comment by lifepillar** [comment]
Please provide more information (which Vim's version? Which terminal? Which OS?), and the steps to reproduce it.

**Comment by lifepillar** [comment]
Closing as stale.
