### ISSUE TITLE
How can I disable italics?

### ISSUE THREAD

**Issue by eggbean** [lifepillar/vim-gruvbox8#49]
With the gruvbox theme I can disable italics with:
```
" gruvbox colour scheme
let g:gruvbox_italic = 0
```
How can I do this with gruvbox8?

-------
EDIT: Actually I have just realised that this setting doesn't seem to do anything, and I don't get italics either way. But in any case, I would prefer to not have any italics anywhere in vim, as I find them too distracting as they seem to appear in more than just comments.

Or, alternatively, how can I disable italics within single quotes?

**Comment by lifepillar** [comment]
See `:help gruvbox-options`.

**Comment by eggbean** [comment]
@lifepillar Thanks, but I get this error message when I try that:

    E149: Sorry, no help for gruvbox-options

Any idea why this is happening? I'm using  NVIM v0.5.1 and help is working for other things.

**Comment by lifepillar** [comment]
Is the color scheme inside an `opt` directory? In any case, you may find Gruvbox8's help file inside the package's `doc` directory.

**Comment by eggbean** [comment]
I only had the `gruvbox8.vim` file in `$XDG_CONFIG_HOME/nvim/colors`. I've add the files in `doc` now as well. Cheers.

**Comment by eggbean** [comment]
I have this in `init.vim` but they are not turning off italics:

    " gruvbox8 colour scheme
      let g:gruvbox_italics = 0
      let g:gruvbox_italicize_strings = 0

I also tried it with italics on, but italics in strings off, as that is what I want ideally. I don't know why these settings have no effect.

**Comment by lifepillar** [comment]
Are you loading the color scheme *after* those settings?

**Comment by eggbean** [comment]
Ah no, I have had my plugin configuration lines at the end and have not realised that that colour schemes need to be loaded afterwards until now. Everything working as expected now. Cheers.
