### ISSUE TITLE
gruvbox_transp_bg=1 doesn't work in Neovim 0.6

### ISSUE THREAD

**Issue by timsofteng** [lifepillar/vim-gruvbox8#50]
Hello. After some updates I noticed that transparent become unavailable.

vim.o.termguicolors=true
vim.cmd [[ colorscheme gruvbox8  ]]
vim.g.gruvbox_transp_bg=1

this code worked before in nvim but now it doesn't.

**Comment by lifepillar** [comment]
Try putting the command that loads the color scheme at the bottom. Does it change anything?

**Comment by timsofteng** [comment]
@lifepillar Yes!
It works now!
Thanks.
Closing.
