### ISSUE TITLE
Colors table

### ISSUE THREAD

**Issue by ixti** [lifepillar/vim-gruvbox8#52]
Thanks for the remarkable classic vim theme revamp. It's noticed that palette was improved in 256-colour-terminals. I would like to know which colours were tweaked. Having a colours table like in [gruvbox-contrib](https://github.com/gruvbox-community/gruvbox-contrib/blob/5be530c3bcde7f226324ec7974bd1a40a61a59d8/color.table) would help to use those colours in other projects (personally I need that for kitty, delta and tig) :D

**Comment by lifepillar** [comment]
You may find the colors in the files in the `templates` folder. For instance, start with `gruvbox8.colortemplate`, then check the included files. Each line starting with `Color:` defines a color: name, GUI value, 256-color number, and 16-color value.

**Comment by ixti** [comment]
Yeah, I thought there might be a similar table to gruvbox-contrib. :D
But running grep against `templates` did the trick. So, the main changes were to 256-color numbers (and I must say I like the new values better).

**Comment by lifepillar** [comment]
If you feel like formatting those into a table to put it in the Readme, I will gladly accept a pull request :-)
