### ISSUE TITLE
Poor readability of conceal characters

### ISSUE THREAD

**Issue by MoetaYuko** [lifepillar/vim-gruvbox8#53]
conceal characters looks like this:
![image](https://user-images.githubusercontent.com/5774651/159616195-041dff4f-3307-4d9e-9527-d0d885f9d024.png)
the color is pretty close to the background and thus not readable
```
:hi conceal
Conceal        xxx ctermfg=239 guifg=#504945
```

**Comment by lifepillar** [comment]
That is not Gruvbox 8. This is what it should be:

```
Conceal        xxx ctermfg=109 guifg=#83a598
```

which is a blue hue. Are you sure you are using this color scheme?

**Comment by MoetaYuko** [comment]
Oops, sorry for the false-positive report. Another plugin I use (https://github.com/Yggdroot/indentLine) modifies conceal by default and I didn't disable that. It looks nice after configuring to stick w/ the default color.
