### ISSUE TITLE
When using gruvbox8_soft and scrolling away, the background color is only partially applied

### ISSUE THREAD

**Issue by alkim0** [lifepillar/vim-gruvbox8#54]
When I load a file using the gruvbox8_soft, only the initial screen has the background colors I expect. When scrolling away, only the code bits have the correct background color and the parts of the screen with no characters just have the normal gruvbox8 (not soft) background color. Refreshing with <c-l> corrects things, but it's annoying to do this every time.

As a side note, this is in the kitty terminal. The issue does not present itself with gvim.

Here is a video

https://user-images.githubusercontent.com/9775404/206849914-fa969887-44be-4769-8491-4323230ea38e.mp4

**Comment by lifepillar** [comment]
I'd say that this is a kittty-specific issue. Does this help? https://github.com/kovidgoyal/kitty/issues/5617

**Comment by alkim0** [comment]
It does! Thanks for the help
