### ISSUE TITLE
Stupid Question: How to Install this in vim?

### ISSUE THREAD

**Issue by venkatarenduchintala** [lifepillar/vim-gruvbox8#58]
How to install?

**Comment by lifepillar** [comment]
I recommend you create a directory structure that looks like this:

```
.vim
└── pack
    └── colors
        └── start
            └── gruvbox8
```

where `.vim` is the directory inside your home directory that contain your Vim configuration, and `gruvbox8` is this repo. The `colors` name is arbitrary: you may use whatever name you want. But, `pack` and `start` must exist and called that way.

To activate the color scheme, use this command:

    :colorscheme gruvbox8

You may use Tab completion to complete the color scheme's name.

Does this help?

**Comment by sevillaarvin** [comment]
For copy paste:

execute in shell:
```shell
git clone --depth 1 "https://github.com/lifepillar/vim-gruvbox8.git" .vim/pack/default/start/gruvbox8
```

copy to **.vimrc** file:
```vimrc
autocmd vimenter * ++nested colorscheme gruvbox8
```
