### ISSUE TITLE
Can you add a preview photo?

### ISSUE THREAD

**Issue by sandangel** [lifepillar/vim-gruvbox8#6]
Can you add a preview photos? Does this work with lightline and vim airline?

**Comment by lifepillar** [comment]
>Can you add a preview photos?

Ok, although this looks essentially like [Gruvbox](https://github.com/morhetz/gruvbox).

>Does this work with lightline and vim airline?

I have explicitly removed any scripts because I use my own custom status line. You may copy the configuration for lightline/vim airline from Gruvbox's repository into your own `autoload` folder, I guess.

**Comment by taigacute** [comment]
@sandangel  hi  here
![56280845-a6bfd580-613d-11e9-857a-d81f2633eeab](https://user-images.githubusercontent.com/41671631/56627826-048e7900-667a-11e9-8fcd-1954db71c454.png)
