### ISSUE TITLE
SignColumn bg color

### ISSUE THREAD

**Issue by taigacute** [lifepillar/vim-gruvbox8#9]
i checked the bg of  SignColumn  is none . but i got bg color. dont know what happend
![2](https://user-images.githubusercontent.com/41671631/58532908-92312b80-8219-11e9-8d0a-da71395f4520.png)

**Comment by taigacute** [comment]
```
verbatim
if !has('gui_running') && get(g:, '@optionprefix_transp_bg', 0)
endverbatim
    # Transparent background
    Normal       fg1    none
    CursorLineNr yellow none
    FoldColumn   grey   none
    SignColumn   fg1    none
    VertSplit    bg3    none
verbatim
else
endverbatim
    # Opaque background
    Normal       fg1    bg0
    CursorLineNr yellow bg1
    FoldColumn   grey   bg1
    SignColumn   fg1    bg1
    VertSplit    bg3    bg0
verbatim
endif
endverbatim


```

**Comment by lifepillar** [comment]
That is by design. By default, the sign column has the same background as other “structural” assets such as the status line and vertical splits. `SignColumn` has a transparent background only when you set `g:gruvbox_transp_bg=1`. The relevant line in the snippet you've pasted is:

```
    SignColumn   fg1    bg1
```

and not

```
    SignColumn   fg1    none
```

**Comment by lifepillar** [comment]
Correction: actually, vertical splits have a transparent background in Gruvbox 8.

**Comment by taigacute** [comment]
@lifepillar   see this
```
  if !has('gui_running') && get(g:, 'gruvbox_transp_bg', 0)
    hi Normal ctermfg=187 ctermbg=NONE guifg=#ebdbb2 guibg=NONE guisp=NONE cterm=NONE gui=NONE
    hi CursorLineNr ctermfg=214 ctermbg=NONE guifg=#fabd2f guibg=NONE guisp=NONE cterm=NONE gui=NONE
    hi FoldColumn ctermfg=102 ctermbg=NONE guifg=#928374 guibg=NONE guisp=NONE cterm=NONE gui=NONE
    hi SignColumn ctermfg=187 ctermbg=NONE guifg=#ebdbb2 guibg=NONE guisp=NONE cterm=NONE gui=NONE
    hi VertSplit ctermfg=59 ctermbg=NONE guifg=#665c54 guibg=NONE guisp=NONE cterm=NONE gui=NONE

```
i use iterm2 and neovim .`echo !has('gui_running')`I got 1,`get(g:, 'gruvbox_transp_bg', 0)` i got 0
but the minnal vimrc i didnt set `gruvbox_transp_bg ` by default is 0,

**Comment by taigacute** [comment]
close, thanks .i know what happend

**Comment by lifepillar** [comment]
Ok. FYI, `SignColumn` looks the same as in the original Gruvbox.

**Comment by taigacute** [comment]
yes, i would like the bg of SignColumn is none when i set `set sighncolumn=yes`,

**Comment by lifepillar** [comment]
Please reopen this then.

**Comment by taigacute** [comment]
just add `hi SignColumn ctermbg=NONE guibg=NONE` in my vimconfig
